title: 職務経歴書
description: クラウドインフラ構築・保守・運用の専門
author: 福山和規
github_username: wan0ri

# Jekyll設定
# GitHub Pages用のプラグイン設定
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag

# ページ設定
permalink: /:title/
markdown: kramdown
highlighter: rouge
relative_links:
  enabled: true
  collections: true

# 除外ファイル
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# サイト設定
lang: ja
timezone: Asia/Tokyo

# ナビゲーション
show_excerpts: true

# GitHub Pages用の追加設定
# リポジトリ名が"resume"の場合、baseurlは"/resume"が正しい
baseurl: "/resume"
url: "https://wan0ri.github.io"
